### PR TITLE
Add slimyboyos:slimes_cannot_absorb tag

### PR DESCRIPTION
**Pull request by williambl**
# Motivation

See #8.

# Content

This PR adds a new item tag, `slimyboyos:slimes_cannot_absorb`. Items in this tag will not be absorbed by slimes.

### CODE REVIEW

**Comment by jaredlll08** [comment]
Please can you rename "blacklist" to "blocklist", otherwise this looks great! Thanks!

**Comment by williambl** [comment]
Sure. I could alternatively rename it to `slimes_cannot_absorb` to be more consistent with vanilla? (which, e.g., uses `lava_pool_stone_cannot_replace`, `snow_layer_cannot_survive_on`)

**Comment by jaredlll08** [comment]
`slimes_cannot_absorb` sounds good

**Comment by williambl** [comment]
All done

**Comment by jaredlll08** [comment]
Thanks!

**Pull request merged**
